//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO
    {
        public EQUIPO()
        {
            this.USER_STORY = new HashSet<USER_STORY>();
        }

        [KEY]
        public int ID { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public Nullable<int> IDROL { get; set; }
        public Nullable<int> IDPROYECTO { get; set; }
    
        public virtual PROYECTO PROYECTO { get; set; }
        public virtual ROL ROL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<USER_STORY> USER_STORY { get; set; }
    }
}
