//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class INTERES
    {
        public INTERES()
        {
            this.STAKEHOLDER = new HashSet<STAKEHOLDER>();
        }

        [Key]
        public int ID { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<STAKEHOLDER> STAKEHOLDER { get; set; }
    }
}
