//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PROYECTO
    {
        public PROYECTO()
        {
            this.CRITERIOS_ACEPTACION = new HashSet<CRITERIOS_ACEPTACION>();
            this.EQUIPO = new HashSet<EQUIPO>();
            this.RELEASE = new HashSet<RELEASE>();
            this.RIESGO = new HashSet<RIESGO>();
            this.STAKEHOLDER = new HashSet<STAKEHOLDER>();
        }
    
        public int ID { get; set; }


        [Display(Name = "Numero de Sprints")]
        public Nullable<int> NUM_SPRINTS { get; set; }

        [Required]
        [Display(Name = "Numero de Releases")]
        public Nullable<int> NUM_RELEASES { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string DESCRIPCION { get; set; }

        [Key]
        public virtual ICollection<CRITERIOS_ACEPTACION> CRITERIOS_ACEPTACION { get; set; }
        public virtual ICollection<EQUIPO> EQUIPO { get; set; }
        public virtual ICollection<RELEASE> RELEASE { get; set; }
        public virtual ICollection<RIESGO> RIESGO { get; set; }
        public virtual ICollection<STAKEHOLDER> STAKEHOLDER { get; set; }
    }
}
