//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELEASE
    {
        public RELEASE()
        {
            this.SPRINT = new HashSet<SPRINT>();
        }

        [KEY]
        public int ID { get; set; }
        public Nullable<int> IDPROYECTO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
    
        public virtual PROYECTO PROYECTO { get; set; }
        public virtual ICollection<SPRINT> SPRINT { get; set; }
    }
}
