//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIESGO
    {
        public RIESGO()
        {
            this.PLAN_ACCION = new HashSet<PLAN_ACCION>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDPROYECTO { get; set; }
        public Nullable<int> IDESTRATEGIA { get; set; }
        public string DESCRIPCION_CORTA { get; set; }
        public string DESC_DETALLADA { get; set; }
        public Nullable<int> PROBABILIDAD { get; set; }
    
        public virtual ESTRATEGIA ESTRATEGIA { get; set; }
        public virtual ICollection<PLAN_ACCION> PLAN_ACCION { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
