//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SPRINT
    {
        public SPRINT()
        {
            this.SPRINT_RETROSPECTIVE = new HashSet<SPRINT_RETROSPECTIVE>();
            this.SPRINT_REVIEW = new HashSet<SPRINT_REVIEW>();
            this.USER_STORY = new HashSet<USER_STORY>();
        }

        [Key]
        public int ID { get; set; }
        public Nullable<int> IDRELEASE { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FINAL { get; set; }
    
        public virtual RELEASE RELEASE { get; set; }
        public virtual ICollection<SPRINT_RETROSPECTIVE> SPRINT_RETROSPECTIVE { get; set; }
        public virtual ICollection<SPRINT_REVIEW> SPRINT_REVIEW { get; set; }
        public virtual ICollection<USER_STORY> USER_STORY { get; set; }
    }
}
