//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPRINT_RETROSPECTIVE
    {
        public int ID { get; set; }
        public Nullable<int> IDSPRINT { get; set; }
        public string COMENTARIO { get; set; }
    
        public virtual SPRINT SPRINT { get; set; }
    }
}
