//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class STAKEHOLDER
    {

        [Key]
        public int ID { get; set; }
        public Nullable<int> IDPODER { get; set; }
        public Nullable<int> IDINTERES { get; set; }
        public Nullable<int> IDPROYECTO { get; set; }
        public string NOMBRE { get; set; }
        public string AP1 { get; set; }
        public string AP2 { get; set; }
        public string CELULAR { get; set; }
        public string EMPRESA { get; set; }
        public string EMAIL { get; set; }
        public string DIRECCION { get; set; }
        public string EXPECTATIVA { get; set; }
    
        public virtual INTERES INTERES { get; set; }
        public virtual PODER PODER { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
