//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        [KEY]
        public int ID { get; set; }
        public Nullable<int> IDUSERSTORY { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> ESFUERZO_INVERTIDO { get; set; }
    
        public virtual USER_STORY USER_STORY { get; set; }
    }
}
