//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TAREA
    {
        [Key]
        public int ID { get; set; }


        [Display(Name = "User Story")]
        public Nullable<int> IDUSERSTORY { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NOMBRE { get; set; }

        [Required]
        [Display(Name = "Esfuerzo en Horas")]
        public Nullable<int> ESFUERZO_INVERTIDO { get; set; }
    
        public virtual USER_STORY USER_STORY { get; set; }
    }
}
