//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_STORY
    {
        public USER_STORY()
        {
            this.TAREA = new HashSet<TAREA>();
        }

        [KEY]
        public int ID { get; set; }
        public Nullable<int> IDPUNTOSESTIM { get; set; }
        public Nullable<int> IDPRIORIDAD { get; set; }
        public Nullable<int> IDSPRINT { get; set; }
        public Nullable<int> IDESTADO { get; set; }
        public Nullable<int> IDTIPO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> DURACION_PLANEADA { get; set; }
        public Nullable<int> TIEMPO_GASTADO { get; set; }
        public Nullable<int> TIEMPO_RESTANTE { get; set; }
        public Nullable<int> PROPIETARIO { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual PRIORIDAD PRIORIDAD { get; set; }
        public virtual PUNTOS_ESTIMACION PUNTOS_ESTIMACION { get; set; }
        public virtual SPRINT SPRINT { get; set; }
        public virtual ICollection<TAREA> TAREA { get; set; }
        public virtual TIPO TIPO { get; set; }
    }
}
