//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.EQUIPO = new HashSet<EQUIPO>();
        }

        [KEY]
        public int ID { get; set; }
        public string AP1 { get; set; }
        public string AP2 { get; set; }
        public string EMAIL { get; set; }
        public string CELULAR { get; set; }
        public string NICK { get; set; }
        public string CONTRASENNIA { get; set; }
    
        public virtual ICollection<EQUIPO> EQUIPO { get; set; }
    }
}
